version: "3.8"
services:
  slave1:
    build: 
      context: ./backend
      dockerfile: Dockerfile    
    environment:
      - BACK_NAME= SERVER 1
    hostname: nodeapp1

  slave2:
    build: 
      context: ./backend
      dockerfile: Dockerfile        
    environment:
      - BACK_NAME= SERVER 2
    hostname: nodeapp2

  slave3:
    build: 
      context: ./backend
      dockerfile: Dockerfile        
    environment:
      - BACK_NAME= SERVER 3   
    hostname: nodeapp3
  
  nginx:
    image: nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - slave1
      - slave2
      - slave3
  
    